name: Tinitiate Github Actions Tutorial
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4

      - name: Print Message in Workflow
        run: echo "This message is from the workflow!"      
      
      - name: Run the custom action
        id: print-echo
        uses: ./github/actions/python-action

#  Run-PSScriptAnalyzer-on-Windows:
#    name: Run PSScriptAnalyzer on Windows
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Install PSScriptAnalyzer module
#        shell: pwsh
#        run: |
#          Set-PSRepository PSGallery -InstallationPolicy Trusted
#          Install-Module PSScriptAnalyzer -ErrorAction Stop
#      - name: Get list of rules
#        shell: pwsh
#        run: |
#          Get-ScriptAnalyzerRule
